name: Jekyll site CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Inject Slug/Short Variables
      uses: rlespinasse/github-slug-action@v2.x

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tech.yonebi-version-1
        #name: tech.yonebi-${{ github.ref }}-${{ github.run_id }}-${{ github.run_number }}
        path: ./dist/tech.yonebi

  deploy:
    runs-on: ubuntu-latest
    need: 
      - build

    steps:
      - name: Inject Slug/Short Variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: tech.yonebi-version-1
          path: 'build'

      - name: Deploy to OVH Hosting
        uses: pitscher/ovh-deploy-hosting-action@v1
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
          OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
          OVH_HOSTING_DOMAIN: ftp.cluster029.hosting.ovh.net