name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use node 19
    - uses: actions/setup-node@v3
    with: 
      node-version: 19

    - name: Install dependencies
      run: npm install 

    - name: Build project
      run: npm run build

    - name: Inject slug/short variables  
      uses: rlespinasse/github-slug-action@v2.x

    - name: Upload artifact  
      uses: actions/upload-artifact@v2
      with:
        name: tech.yonebi-${{ github.ref }}-${{ github.run_id }}-${{ github.run_number }}
        path: ./dist/tech.yonebi

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

    name: Deploy
    run: 

  #deploy:
  #  runs-on: ubuntu-latest
  #  name: Deploy my nice code
  #  steps:
  #  - name: Deploy to OVH hosting
  #    uses: pitscher/ovh-deploy-hosting-action@v1
  #    env:
  #      OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
  #      OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
  #      OVH_HOSTING_DOMAIN: ftp.cluster029.hosting.ovh.net
  #     REPOSITORY_NAME: tech.yonebi
  #      REPOSITORY_URL: https://github.com/mayel15/tech.yonebi"""